---
application::domain_name : gunnery.com
application::name : gunnery

application::user : gunnery

application::root_path : /var/gunnery
application::repository_path : "%{hiera('application::root_path')}"
application::path : "%{hiera('application::repository_path')}/%{hiera('application::name')}"
application::requirements_path : "%{hiera('application::repository_path')}/requirements/%{::environment}.txt"
application::secure_path : "%{hiera('application::root_path')}/secure"
application::log_path : "%{hiera('application::root_path')}/log"
application::run_path : "%{hiera('application::root_path')}/run"
application::virtualenv_path : "%{hiera('application::root_path')}/virtualenv/%{::environment}"

postgresql::user : gunnery

celery::workers : 1
celery::concurrency : 8